-- MySQL Script generated by MySQL Workbench
-- Thu Oct 29 15:12:19 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`User` ;

CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `User_ID` INT NOT NULL AUTO_INCREMENT,
  `Password` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(100) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Phone` VARCHAR(15) NULL DEFAULT NULL,
  `Admin` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`User_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Found_Listing`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Found_Listing` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Found_Listing` (
  `Listing_ID` INT NOT NULL,
  `User_ID` INT NOT NULL,
  `Type` VARCHAR(45) NOT NULL,
  `Color` VARCHAR(45) NOT NULL,
  `Item_Description` TEXT NOT NULL,
  `Date_Found` DATETIME NOT NULL,
  `Location_Found` VARCHAR(45) NOT NULL,
  `Date_Returned` DATETIME NULL,
  `Location_Returned` VARCHAR(45) NULL,
  `Date_Posted` DATETIME NOT NULL,
  PRIMARY KEY (`Listing_ID`),
  INDEX `found_posted_by_idx` (`User_ID` ASC),
  CONSTRAINT `found_posted_by`
    FOREIGN KEY (`User_ID`)
    REFERENCES `mydb`.`User` (`User_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Lost_Listing`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Lost_Listing` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Lost_Listing` (
  `Listing_ID` INT NOT NULL AUTO_INCREMENT,
  `User_ID` INT NOT NULL,
  `Type` VARCHAR(45) NOT NULL,
  `Color` VARCHAR(45) NOT NULL,
  `Item_Description` TEXT NOT NULL,
  `Date_Lost` DATETIME NOT NULL,
  `Location_Lost` VARCHAR(45) NOT NULL,
  `Date_Posted` DATETIME NOT NULL,
  PRIMARY KEY (`Listing_ID`),
  INDEX `lost_posted_by_idx` (`User_ID` ASC),
  CONSTRAINT `lost_posted_by`
    FOREIGN KEY (`User_ID`)
    REFERENCES `mydb`.`User` (`User_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Image` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Image` (
  `Image_ID` INT NOT NULL AUTO_INCREMENT,
  `User_ID` INT NOT NULL,
  `Listing_ID` INT NOT NULL,
  `Image_Location` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Image_ID`),
  INDEX `owner_of_photo_idx` (`User_ID` ASC),
  INDEX `found_listing_idx` (`Listing_ID` ASC),
  CONSTRAINT `owner_of_photo`
    FOREIGN KEY (`User_ID`)
    REFERENCES `mydb`.`User` (`User_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `found_listing`
    FOREIGN KEY (`Listing_ID`)
    REFERENCES `mydb`.`Found_Listing` (`Listing_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `lost_listing`
    FOREIGN KEY (`Listing_ID`)
    REFERENCES `mydb`.`Lost_Listing` (`Listing_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Closed_Item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Closed_Item` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Closed_Item` (
  `Closed_ID` INT NOT NULL,
  `Listing_ID` INT NULL,
  `Recovered_By_Owner` TINYTEXT NOT NULL,
  PRIMARY KEY (`Closed_ID`),
  INDEX `closed_lost_idx` (`Listing_ID` ASC),
  CONSTRAINT `closed_found`
    FOREIGN KEY (`Listing_ID`)
    REFERENCES `mydb`.`Found_Listing` (`Listing_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `closed_lost`
    FOREIGN KEY (`Listing_ID`)
    REFERENCES `mydb`.`Lost_Listing` (`Listing_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Identity_Waiver`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Identity_Waiver` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Identity_Waiver` (
  `User_ID` INT NOT NULL,
  `Closed_ID` INT NOT NULL,
  `Waiver` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`User_ID`, `Closed_ID`),
  INDEX `closed_item_idx` (`Closed_ID` ASC),
  CONSTRAINT `user_waiver`
    FOREIGN KEY (`User_ID`)
    REFERENCES `mydb`.`User` (`User_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `closed_item`
    FOREIGN KEY (`Closed_ID`)
    REFERENCES `mydb`.`Closed_Item` (`Closed_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
